server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: PURCHASE-SERVICE
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/api/purchase/**

eureka:
  instance:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/